name: Check Pull Request
on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop
jobs:
  test:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps: 
      - name: Descargar codigo
        uses: actions/checkout@v2
      - name: Correr Unit Test
        run: chmod +x ./gradlew && ./gradlew cleanTestDebugUnitTest testDebugUnitTest --debug
  build:
    name: build app
    runs-on: ubuntu-latest
    steps:
      - name: Descargar codigo
        uses: actions/checkout@v2
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Build the app
        run: ./gradlew assembleDebug
      - name: Upload apk
        uses: actions/upload-artifact@v2
        with:
          name: debug apk
          path: app/build/outputs/apk/debug/app-debug.apk
