name : Prueba Unit Tests
on: [push]

jobs:
  primera:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps: 
      - name: Descargar codigo
        uses: actions/checkout@v2
      - name: Listado de archivos
        run: ls
      - name: Correr Unit Test
        run: gradle test
      - name: Build the app
        run: ./gradlew assembleDebug
      - name: Upload apk
        uses: actions/upload-artifact@v2
        with:
          name: debug apk
          path: app/build/outputs/apk/debug/app-debug.apk
